CREATE TABLE USERS(
  USER_ID NUMBER CONSTRAINT USERS_PK PRIMARY KEY,
  LOGIN VARCHAR2(100),
  PASSWORD_HASH VARCHAR2(100),
  LAST_LOGIN DATE
);

CREATE TABLE MESSAGE(
  MESSAGE_ID NUMBER CONSTRAINT MESSAGE_PK PRIMARY KEY ,
  TEXT VARCHAR2(200),
  MOD NUMBER CONSTRAINT USERS_FK REFERENCES USERS(USER_ID)
);

CREATE TABLE ALLOWED_MESSAGES (
  MESSAGE_ID NUMBER CONSTRAINT MSG_ID_FK REFERENCES MESSAGE(MESSAGE_ID),
  USER_ID NUMBER CONSTRAINT USR_ID_FK REFERENCES USERS(USER_ID),
  CONSTRAINT ALL_MSG_PK PRIMARY KEY (MESSAGE_ID, USER_ID)
);

CREATE SEQUENCE users_seq
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE message_seq
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1;
