DROP TABLE ALLOWED_MESSAGES;
DROP TABLE MESSAGE;
DROP TABLE PASSWORDS;
DROP TABLE USERS;
DROP TABLE BAD_USERS;

DROP SEQUENCE users_seq;
DROP SEQUENCE bad_users_seq;
DROP SEQUENCE pass_seq;
DROP SEQUENCE message_seq;